"""
Reasoning Engine Facade.

Re-exports the reasoning_engine sub-package for backward compatibility.
"""

from __future__ import annotations

from worker.agents.reasoning_engine import (
    EFFECT_TYPES,
    EVIDENCE_SOURCE_TIERS,
    EVIDENCE_TYPE_TO_TIER,
    OUTCOMES,
    RELEVANCE_LEVELS,
    _EFFECT_DIRECTION,
    _RELEVANCE_WEIGHT,
    _build_case_summary,
    _build_reasoning_trace,
    _check_credit_not_processed,
    _check_duplicate,
    _check_item_not_received,
    _check_processing_error,
    _check_subscription,
    _check_unauthorized,
    _confidence_band,
    _extract_delivery_address,
    _extract_delivery_date,
    _extract_report_date,
    _extract_shipping_address,
    _fact_to_statement,
    _generate_explanation,
    _get_llm_client,
    _llm_evaluate_evidence_batch,
    _llm_evaluate_policies,
    _llm_json_call,
    _parse_date,
    detect_conflicts,
    fair_weighing,
    generate_findings,
    get_source_tier,
    run_deterministic_checks,
    run_semantic_evaluations,
    synthesize_decision,
)

__all__ = [
    "RELEVANCE_LEVELS",
    "EFFECT_TYPES",
    "OUTCOMES",
    "EVIDENCE_SOURCE_TIERS",
    "EVIDENCE_TYPE_TO_TIER",
    "get_source_tier",
    "_RELEVANCE_WEIGHT",
    "_EFFECT_DIRECTION",
    "_get_llm_client",
    "_llm_json_call",
    "generate_findings",
    "_fact_to_statement",
    "run_deterministic_checks",
    "_parse_date",
    "_extract_delivery_date",
    "_extract_report_date",
    "_extract_shipping_address",
    "_extract_delivery_address",
    "_check_item_not_received",
    "_check_unauthorized",
    "_check_duplicate",
    "_check_credit_not_processed",
    "_check_subscription",
    "_check_processing_error",
    "run_semantic_evaluations",
    "_build_case_summary",
    "_llm_evaluate_evidence_batch",
    "_llm_evaluate_policies",
    "detect_conflicts",
    "fair_weighing",
    "synthesize_decision",
    "_confidence_band",
    "_generate_explanation",
    "_build_reasoning_trace",
]
